// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'C:/Users/Kien-PC/OneDrive/Desktop/Dự Án LTW_2026/HTQLTS_2026_2/RIPT1307-04-2026-Nh-m12-KTHP/frontend/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
